version: '3.8'

services:
  bitkisorgu_app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: bitkisorgusu_container
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
