version: '3.8'

services:
  # Güvenli Backend Servisi (BCrypt + SQLite API)
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    restart: always

  # Web Ön Yüz Servisi
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - api
    restart: always
